### ISSUE TITLE
Add continuous integration

### ISSUE THREAD

**Issue by arthurrump** [arthurrump/Zermelo.API#8]
This used to live on VSTS, but apparently even Microsoft doesn't have VS2017 running on their buildservers yet. The preferred way would now be [AppVeyor](https://ci.appveyor.com/project/arthurrump/zermelo-api), because it's more open than VSTS. However, they don't have VS2017 running yet, either, so I'll have to wait for that.

**Comment by arthurrump** [comment]
`dev`: [![Build status](https://ci.appveyor.com/api/projects/status/h4l0t4ch01pgtr33/branch/dev?svg=true)](https://ci.appveyor.com/project/arthurrump/zermelo-api/branch/dev)

`master`: [![Build status](https://ci.appveyor.com/api/projects/status/h4l0t4ch01pgtr33/branch/master?svg=true)](https://ci.appveyor.com/project/arthurrump/zermelo-api/branch/master)

**Comment by arthurrump** [comment]
And don't forget to build the docs!

**Comment by arthurrump** [comment]
```
version: 3.0.{build}
image: Visual Studio 2017 RC
init:
- ps: dotnet --info
build_script:
- ps: >-
    dotnet restore

    dotnet build -c Release
test_script:
- ps: dotnet test .\Zermelo.API.Tests\Zermelo.API.Tests.csproj --no-build -c Release
artifacts:
- path: '**\Zermelo.API.*.nupkg'
  name: nupkg
- path: .\Zermelo.API\bin\Release\**\Zermelo.API.dll
  name: dll
deploy:
- provider: NuGet
  api_key:
    secure: 9+WOr6sGkJT4ltYLPgIRNCambkznLpX/JocQG004a0nZVacqmy3268EFgvnmFWlo
  skip_symbols: true
  artifact: nupkg
  on:
    branch: master
- provider: GitHub
  tag: v$(appveyor_build_version)
  auth_token:
    secure: LvgYo8wrp1PNQN43IUQSgUAoKDLFJ1CS9GNh7b4TGZlv2ZgYoNW/4P2jjpU/Pyu+
  artifact: dll
  on:
    branch: master
```

TODO:
- [ ] Build the docs
- [ ] Release docs to GitHub Pages (as a deploy)
- [ ] Write a script to replace .csproj versions with AppVeyor version (includes builds)

AppVeyor has something called AssemblyInfo patching, which would usually take care of the last point, but those versions aren't used by `dotnet build`, so the versions in .csproj should be replaced.
